# ! PLEASE NOTE THAT THIS IS ONLY FOR INTERNAL USE AND THE FILE IS UPLOADED ON GITHUB FOR CONVENIENCE  

stages:
  - docker

build_docker_image:
  stage: docker
  tags:
    - shell
  script:
    - echo "Building docker images ..."
    - echo "Building api:"
    - docker image build -t esid/backend-api:latest api/src/api
    - echo "Building worker:"
    - docker image build -t esid/backend-worker:latest api/src/worker
    - echo "Building docker images successful"
    - docker image save esid/backend-api:latest esid/backend-worker:latest | gzip > esid-backend_latest.tar.gz
    - echo "Saved images to file"
  artifacts:
    when: on_success
    paths:
      - esid-backend_latest.tar.gz
    expire_in: "1 hour"
