# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class GridcellData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GridcellData - a model defined in OpenAPI

        timestamp: The timestamp of this GridcellData [Optional].
        cell: The cell of this GridcellData [Optional].
        value: The value of this GridcellData [Optional].
    """

    timestamp: Optional[str] = Field(alias="timestamp", default=None)
    cell: Optional[str] = Field(alias="cell", default=None)
    value: Optional[float] = Field(alias="value", default=None)

GridcellData.update_forward_refs()
