# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from app.models.compartment import Compartment


class Model(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Model - a model defined in OpenAPI

        name: The name of this Model [Optional].
        description: The description of this Model [Optional].
        aggregations: The aggregations of this Model [Optional].
        compartments: The compartments of this Model.
        groups: The groups of this Model.
        parameter_definitions: The parameter_definitions of this Model.
        id: The id of this Model.
    """
    id: str = Field(alias="id")
    name: Optional[str] = Field(alias="name", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    compartments: List[Compartment] = Field(alias="compartments")
    groups: List[List[str]] = Field(alias="groups")
    aggregations: Optional[List[List]] = Field(alias="aggregations", default=None)
    parameter_definitions: List[List[str]] = Field(alias="parameterDefinitions")

Model.update_forward_refs()
