# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NewNodeListAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewNodeListAllOf - a model defined in OpenAPI

        node_ids: The node_ids of this NewNodeListAllOf [Optional].
    """

    node_ids: Optional[List[List]] = Field(alias="nodeIds", default=None)

NewNodeListAllOf.update_forward_refs()
