# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NewGroupAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewGroupAllOf - a model defined in OpenAPI

        category: The category of this NewGroupAllOf [Optional].
    """

    category: Optional[str] = Field(alias="category", default=None)

NewGroupAllOf.update_forward_refs()
