# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from app.models.compartment import Compartment
from app.models.compartment_aggregation import CompartmentAggregation


class NewModelAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewModelAllOf - a model defined in OpenAPI

        aggregations: The aggregations of this NewModelAllOf [Optional].
        compartments: The compartments of this NewModelAllOf.
        groups: The groups of this NewModelAllOf.
        parameter_definitions: The parameter_definitions of this NewModelAllOf.
    """

    aggregations: Optional[List[CompartmentAggregation]] = Field(alias="aggregations", default=None)
    compartments: List[Compartment] = Field(alias="compartments")
    groups: List[List] = Field(alias="groups")
    parameter_definitions: List[List] = Field(alias="parameterDefinitions")

NewModelAllOf.update_forward_refs()
