# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunSimulations(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunSimulations - a model defined in OpenAPI

        run_id: The id of this RunSimulations [Optional].
        scenario_id: The id of this scenario_id [Optional].
    """

    run_id: Optional[str] = Field(alias="run_id", default=None)
    scenario_id: Optional[str] = Field(alias="scenario_id", default=None)


RunSimulations.update_forward_refs()
