# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ScenarioRunsRunIdListInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ScenarioRunsRunIdListInner - a model defined in OpenAPI

        run_id: The run_id of this ScenarioRunsRunIdListInner [Optional].
        timestamp: The timestamp of this ScenarioRunsRunIdListInner [Optional].
    """

    run_id: Optional[str] = Field(alias="run_id", default=None)
    timestamp: Optional[str] = Field(alias="timestamp", default=None)


ScenarioRunsRunIdListInner.update_forward_refs()
