services:
  worker:
    build: ./src/worker
    restart: always
    networks:
      - backnet
    depends_on:
      - redis
    volumes:
      - ./src/worker:/worker
      - ${VOLUME_DIR}/input:/worker/input
    env_file:
      - .docker-env
  api:
    build: ./src/api
    restart: always
    networks:
      - backnet
    env_file:
      - .docker-env
    volumes:
      - ./src/api/:/api
      - ${VOLUME_DIR}/input:/api/input/
    ports:
      - ${API_PORT}:8000
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    restart: always
    image: redis
    volumes:
      - ${VOLUME_DIR}/redis_data:/var/lib/redis/data
    networks:
      - backnet
    ports:
      - 6379:6379
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ${VOLUME_DIR}/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .docker-env
    networks:
      - backnet
    ports:
      - ${DB_PORT}:5432

networks:
  backnet:

# volumes:
#   input:
#   output:
#   postgres_data:
#   redis_data:
